name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Set up Rust target
        run: |
          rustup target add x86_64-pc-windows-gnu
          rustup target add x86_64-unknown-linux-gnu

      - name: Build
        run: |
          cargo build --target x86_64-pc-windows-gnu --release
          cargo build --target x86_64-unknown-linux-gnu --release 

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-alpha
          name: Release ${{ github.ref_name }}-alpha
          draft: false
          prerelease: true
          files:
            ./target/x86_64-pc-windows-gnu/release/wttr-cli.exe
            ./target/x86_64-unknown-linux-gnu/release/wttr-cli