name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu ]

    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-chef
        run: cargo install cargo-chef

      - name: Prepare Cargo Dependencies
        run: cargo chef prepare --recipe-path recipe.json

      - name: Cache Built Dependencies
        uses: actions/cache@v4
        with:
          path: target/chef
          key: deps-${{ runner.os }}-${{ hashFiles('**/recipe.json') }}
          restore-keys: |
            deps-${{ runner.os }}-

      - name: Build Dependency Layer
        run: cargo chef cook --release --recipe-path recipe.json

      - name: Install cross-compilation tools
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64

      - name: Set up Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --target ${{ matrix.target }} --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            ./target/x86_64-pc-windows-gnu/release/wttr-cli.exe
            ./target/x86_64-unknown-linux-gnu/release/wttr-cli
          overwrite: true

  release:
    name: Release ${{ github.ref }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
          files: |
            ./target/x86_64-pc-windows-gnu/release/wttr-cli.exe
            ./target/x86_64-unknown-linux-gnu/release/wttr-cli